POST localhost:8888/accounts
Content-Type: application/json

{
  "id": 1,
  "number": "1111",
  "balance": 20000
}

###

GET localhost:8888/accounts/1
Content-Type: application/json

###

GET localhost:8888/accounts
Content-Type: application/json

###

DELETE localhost:8888/accounts/1