POST /residents/9/relationship
Content-Type: application/json
Host: localhost:9090

{
  "familySerialNumber": 3,
  "familyRelationshipCode": "부"
}

###

PUT /residents/9/relationship/3
Content-Type: application/json
Host: localhost:9090

{
  "familyRelationshipCode": "모"
}

###

DELETE /residents/10/relationship/123
Host: localhost:9090