POST /household/1/movement
Host: localhost:9090
Content-Type: application/json

{
  "householdSerialNumber": 10,
  "houseMovementReportDate": "2022-12-04T00:00:00",
  "houseMovementAddress": "광주광역시"
}

